---
# tasks file for net2grid.repo-priority
- name: Disable priority flags on repositories
  replace:
    dest: "/etc/yum.repos.d/{{ item }}"
    regexp: '^failovermethod=priority$'
    replace: '#failovermethod=priority'
  with_items: "{{ repo_priority }}"

- name: Exclude packages from repositories
  ini_file:
    dest: "/etc/yum.repos.d/{{ item.repo }}"
    section: "{{ item.section }}"
    option: exclude
    value: "{{ item.package }}"
  with_items: "{{ repo_exclude }}"
